assets: /home/wjq/workspace/venvs/libero_act/lib/python3.12/site-packages/libero/libero/assets
bddl_files: /home/wjq/workspace/venvs/libero_act/lib/python3.12/site-packages/libero/libero/bddl_files
benchmark_root: /home/wjq/workspace/venvs/libero_act/lib/python3.12/site-packages/libero/libero
datasets: /home/wjq/research-assets/libero_dcta/datasets
init_states: /home/wjq/workspace/venvs/libero_act/lib/python3.12/site-packages/libero/libero/init_files
